name: Daily Repo Update

on:
  schedule:
    - cron: '30 2 * * *'  # runs daily at 02:30 UTC
  workflow_dispatch:      # allows manual trigger

permissions:
  contents: write #this is required to allow the workflow to push changes back to the repository
  #else The GitHub Actions bot tries to push a commit but as it does NOT have write permission to your repo, the push fails with an error 

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 23f3003994@ds.study.iitm.ac.in
        run: echo "Running daily update"

      - name: Make daily commit
        run: |
          echo "Last update: $(date)" >> daily-log.txt
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add daily-log.txt
          git commit -m "Automated daily update"
          git push
